[hince 이태현] Add: Shop 페이지 카테고리 및 상품 view 작성 및 모델 수정
wecode-bootcamp-korea/11-Hipce-backend pull request #6
Opened 2020-08-25 00:46 UTC by 0417taehyun

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
- 크롤링 결과 중복되는 이미지 사용으로 태그 및 이미지 테이블을 따로 만들지 않고 Product 테이블에 삽입(DB Heat 줄임)
- Shop 페이지 카테고리 섹션 이름과 이미지 데이터를 보내주는 get 방식 API 작성
- Shop 페이지 상품 이름, 이미지(메인, 애니메이션 후), 가격, 태그 이미지를 보내주는 get 방식 API 작성

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- 크롤링을 해 본 결과 hince shop 웹 페이지에서 이미지가 main 이미지 하나와 main 이미지에 마우스를 올렸을 때 나타나는 애니메이션 후 이미지로 동일한 방법으로 중복되어 있는 것을 확인하여 모델을 수정했습니다. 기존과 같은 방식으로 할 경우 이미지 테이블에 접근할 때 디비 히트를 한 번 더 해야하는 문제점이 있다고 판단하여 상품 정보를 보내줄 때 함께 이미지를 포함해서 보내주는 것이 디비 히트가 한 횟수 적어 모델을 수정했습니다.

- 카테고리 및 아래 상품 리스트를 보여주는 API 두 개를 작성했습니다. 두 API 모두 오류 처리를 따로 해 줄 필요 없이 정보만 보내주는 GET방식으로 작성하여 status = 200인 경우(정상적으로 정보를 보내주는 경우)만 작성했으며 프론트 엔드에서 키, 밸류로 Fetch하는 것이 더 편하다고 서로 소통하여 values 쿼리셋을 사용 필요한 부분만 뽑아내 전달했습니다. (예를 들어 id의 경우 굳이 프론트 엔드에게 전달하지 않아도 되서 id 컬럼을 제외했습니다. 함수에 관한 짧은 설명을 혹시 몰라 독스트링으로 적어놨습니다. 지우라면 지우겠습니다.)

- 페이지네이션 세션이 오늘 있다는 것을 들어서 상품 리스트를 보여주는 API의 경우 오늘 세션 이후 프론트 엔드와 맞춰 다시 수정하겠습니다. ( Push 하고 나서 알게 되어 죄송합니다. )

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-25 07:31 UTC, 0417taehyun commented
>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
- 엔드포인트 URL 수정
- 제품별 상세 정보를 보여주는 엔드포인트 제작 (ProductView)

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- 기존 제품 리스틀 보여줄 때 직관적이지 않았던 URL를 수정하였습니다. (category > products)
- 기존 URL Path를 리소스 기준으로 하지 않았던 것을 리소스 기준으로 바꿨습니다. (product/detail > product/<int:id>)
- 제품별 상세 정보를 보여주는 엔드포인트 ProductsView를 만들었습니다. id를 받아 해당 id에 일치하는 제품의 이름, 메인 이미지, 설명 이미지, 가격에 관한 정보만 보내주면 되서 values() 쿼리셋을 사용해 컬럼을 제한했습니다. 버튼을 클릭해서 제품별 상세 정보로 넘어가는 방식이라 요청 과정에서 오류가 발생할 일이 없어서 따로 예외 처리를 해주지 않았습니다.


## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-25 16:53 UTC, 0417taehyun commented
>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
- 제품 리스트를 보여주는 엔드포인트에 컬러 필터 옵션 추가
- 컬러 전체를 보여주는 엔드포인트 추가

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- 기존 단순 제품 리스트를 보여주던 엔드포인트에 prefetch_related를 사용해 데이터베이스 접근 속도를 빠르게 하였으며, if문을 활용해 어떤 색깔도 선택하지 않은 디폴트 값을 처리해주었습니다. 이후 프론트엔드에 키-밸류 형식으로 데이터를 전달하기만 하면 되어서 values() 쿼리셋을 사용했으며 불필요한 정보들을 주지 않기 위해 values() 쿼리셋에 특정 컬럼("name", "main_image", "sub_image", "price", "tag")을 지정했습니다.

아래 첫 번째 이미지의 경우 select_related를 사용했을 때의 속도, 두 번째 이미지의 경우 prefetch_related를 사용했을 때의 속도입니다. 포스트맨을 통해 비교하였으며 거의 유사했으나 평균적인 속도가 prefetch_related가 더 빨라서 선택했습니다.
![1  select_related](https://user-images.githubusercontent.com/63915557/91203952-6bc0af80-e73e-11ea-94ed-755f93f776b5.png)
![2  Prefetch_related](https://user-images.githubusercontent.com/63915557/91204015-7aa76200-e73e-11ea-9edf-8f450829bb69.png)

- 전체 컬러 리스트를 보여주는 엔드포인트를 구현했습니다. 단순히 프론트엔드에 키-밸류 형식으로 데이터를 전달하기만 하면 되어서 values() 쿼리셋을 사용했으며 불필요한 id 등을 주지 않기 위해 values() 쿼리셋에 특정 컬럼("name")을 지정했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-26 02:30 UTC, lordmyshepherd requested changes

2020-08-26 02:30 UTC, lordmyshepherd commented on product/urls.py
> +urlpatterns = [
main urls.py file에 product urls.py를 추가해주셨나요?
(파일이 보이지 않아서 여쭤봐요~)

2020-08-26 02:30 UTC, lordmyshepherd commented on product/urls.py
> +    path('', CategoryView.as_view()),
완전:+1:

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        ''' 만든 이: 이태현
`11 - 15`  주석을 제거해주세요~
code에는 정말 필요한 주석 아니면 남기 않도록 해주세요~
`만든이, 최종 수정` << git history에 남기 때문에 코드를 열어서 확인할 수 있는 정보에요!
`정보, 설명`은 불필요해 보입니다.

이유는 태현님께서 작성해주신 코드는 get method가 설명이 없어도 코드만 보고 쉽게 이해할 수 있기 때문입니다.
이렇게 깔끔하게 작성하시고 주석까지 남겨주시는건 too much!

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        categories = Category.objects.values('name', 'image')
한줄로 바꿀 수 있겠네요!
16 - 20
```
class CategoryView(View):
        def get(self, request):
            return JsonResponse({'categories' : list(Category.objects.values('name', 'image'))}, status = 200)
```

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        '''만든 이: 이태현
마찬가지로 주석은 제거해주세요~
이미 코드를 보고 이해할 수 있습니다~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        categories = Category.objects.values('name', 'image')
return은 한줄로 표현해주세요~
파이썬에서는 한줄에 80자를 넘어가지 않도록 추천하고 있기 때문에 이정도는 충분히 한줄로 표현할 수 있습니다~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        return JsonResponse(
한줄로 수정해주세요~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        color_list    = request.GET.getlist('color', None)
list라는 용어는 잘 사용하지 않습니다~ 

```suggestion
        colors = request.GET.getlist('color', None)
```

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        products      = Product.objects.prefetch_related('color').filter(
한줄로 수정해주세요~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        if color_list:
if 문 없이,
products에서 filter 하실때, filter(category__name=category_name, colo__name__in =color_list)로 수정해보심이 어떤가요?

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        '''만든 이: 이태현
주석 삭제해주세요~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +    def get(self, request, id):
id 보다는 정확하게 product_id로 명시해주는게 좋습니다!

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        colors = Color.objects.values('name')
한줄로 수정해주세요~

2020-08-26 02:30 UTC, lordmyshepherd commented on product/views.py
> +        '''만든 이: 이태현
여기도 주석은 지워주세요~

2020-08-26 03:23 UTC, 0417taehyun commented on product/models.py
> +    collection        = models.ForeignKey('Collection', on_delete = models.CASCADE, null = True)
네! Collection이 없는 경우도 있어서 null = True 로 변경했습니다.

2020-08-26 03:23 UTC, 0417taehyun commented on product/urls.py
> +urlpatterns = [
네네 추가했는데 다음 커밋 때 파일 왜 안 올라갔는지 알아보고 함께 올리도록 하겠습니다.

2020-08-26 03:32 UTC, 0417taehyun commented on product/views.py
> +        if color_list:
위에서 filter(color__name__in = color_list)로 할 경우color_list 가 None일 때가 들어가는데 Color table 의 name 필드에는 None인 경우가 없이 Red, Orange처럼 이름들이 존재합니다. 이때 제품들 중에서는 컬러 필터가 아예 존재하지 않는 필터가 존재해서 디폴트로는 컬러의 여부 상관 없이 전부 보여줘야 한다고 생각하여 category_name 으로만 필터를 하고, 만약에 color_list 에 값이 들어 있을 경우(None이 아니고 ['Red']와 같이 필터가 먹혔을 경우) 해당 카테고리에서 컬러 필터를 거쳐서 보여줘야 하기 때문에 위와 같은 로직을 구현했습니다. 아래 첫 번째 이미지는 Color 테이블에 저장되어 있는 color 들에 관한 데이터고 두 번째는 제품들 중에서 Color가 저장되어 있지 않은 경우입니다. (하나의 제품이 여러 컬러를, 하나의 컬러가 여러 제품을 가질 수 있는 M:N 관계입니다.)

![1  Color](https://user-images.githubusercontent.com/63915557/91252130-e23dcb80-e797-11ea-83af-c34bc286b1e0.png)
![2  Color_list](https://user-images.githubusercontent.com/63915557/91252132-e36ef880-e797-11ea-83e9-32a6cb9c49e6.png)

2020-08-26 07:07 UTC, 0417taehyun commented on product/views.py
> +        products      = Product.objects.prefetch_related('color').filter(
이 부분은 category_name 과 color_list(변수명 colors로 수정)를 한 줄로 작성하라는 말씀이신가요?

2020-08-26 11:10 UTC, 0417taehyun commented
>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
- 제품 리스트 엔드포인트에 search filter 기능 추가
- 제품 리스트 엔드포인트에 tag filter 기능 추가
- 콜렉션 전체를 보여주는 엔드포인트 구현

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- app 이름이 product라서 기존에 shop으로 적었던 url을 products(복수)로 변경하였습니다.
- 제품 리스트 엔드포인트(ProductsView)에 keyword를 받아서 해당하는 문자가 포함되어 있는 제품들을 보여주는 기능을 추가했습니다.
- 제품 리스트 엔드포인트(ProductsView)에 tag를 받아서 해당 태그를 포함하는 제품들을 보여주는 기능을 추가했습니다.
- 컬렉션 리스트 엔드포인트를 구현했습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-08-27 07:26 UTC, lordmyshepherd commented on product/views.py
> +
아래 방법을 사용해보시면 좋을 것 같아요~
```
q = Q()
if keyword:
    q &= Q(name__icontains = keyword)
if tag:
    q &= Q(tag__name)
if colors:
    q &= Q(color__name__in = colors)
...
product = Product.objects.filter(q)
..
```

2020-08-27 07:26 UTC, lordmyshepherd approved these changes

2020-08-27 07:27 UTC, lordmyshepherd commented
LGTM :+1:

2020-08-27 07:27 UTC, merged